# Generated by Django 5.0 on 2023-12-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер участка')),
                ('title', models.CharField(max_length=50, verbose_name='Название участка')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество сотрудника')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('snils', models.CharField(max_length=50, verbose_name='СНИЛС')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Сотрудник кладбища',
                'verbose_name_plural': 'Сотрудники кладбища',
            },
        ),
        migrations.CreateModel(
            name='burial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_burial', models.CharField(max_length=50, verbose_name='Номер захоронения на участке')),
                ('surname_person', models.CharField(max_length=50, verbose_name='Фамилия захороненного')),
                ('name_person', models.CharField(max_length=50, verbose_name='Имя захороненного')),
                ('middlename_person', models.CharField(max_length=50, verbose_name='Отчество захороненного')),
                ('birth_person', models.DateField(verbose_name='Дата рождения захороненного')),
                ('death_person', models.DateField(verbose_name='Дата смерти захороненного')),
                ('area_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Захоронение',
                'verbose_name_plural': 'Захоронения',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='employee_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Обслуживающий сотрудник'),
        ),
    ]
